export const COUNTRY_FLAGS = [
  {
    id: 'sa',
    en: 'Saudi',
    ar: 'السعوديه',
    code: '+966',
    icon: require('../../../assets/img/saudi.png'),
  },
  {
    id: 'qr',
    en: 'Qatar',
    ar: 'قطر',
    code: '+974',
    icon: require('../../../assets/img/qatar.png'),
  },
  {
    id: 'ua',
    en: 'Emirate',
    ar: 'الامارات',
    code: '+971',
    icon: require('../../../assets/img/emirate.png'),
  },
  {
    id: 'ku',
    en: 'Kuwait',
    ar: 'الكويت',
    code: '+965',
    icon: require('../../../assets/img/kuwait.png'),
  },
  {
    id: 'jd',
    en: 'Jordan',
    ar: 'الاردن',
    code: '+962',
    icon: require('../../../assets/img/jordan.png'),
  },
  {
    id: 'bh',
    en: 'Bahrain',
    ar: 'البحرين',
    code: '+973',
    icon: require('../../../assets/img/bahrain.png'),
  },
  {
    id: 'om',
    en: 'Oman',
    ar: 'عمان',
    code: '+968',
    icon: require('../../../assets/img/oman.png'),
  },
  {
    id: 'eg',
    en: 'Egypt',
    ar: 'مصر',
    code: '+20',
    icon: require('../../../assets/img/egypt.png'),
  },
  {
    id: 'ir',
    en: 'Iraq',
    ar: 'العراق',
    code: '+964',
    icon: require('../../../assets/img/iraq.png'),
  },
  {
    id: 'xx',
    en: 'Other',
    ar: 'دوله اخرى',
    code: '+',
    icon: require('../../../assets/img/world.png'),
  },
];
